### ISSUE TITLE
Fails with KeyError: 'wal_buffers' using -V 9.1 against a 9.4.8 Pg (not supported I suppose)

### ISSUE THREAD

**Issue by sammyjava** [gregs1104/pgtune#20]
```
[beans@intermine pgtune]$ psql --version
psql (PostgreSQL) 9.4.8
```
So that's what I'm running, but I tell pgtune that it's 9.1 since that's the latest settings file you've got in the repo:
```
[beans@intermine pgtune]$ ./pgtune -i postgresql.conf -o postgresql.conf.tuned -V 9.1 -c 100 -L
Traceback (most recent call last):
  File "./pgtune", line 698, in <module>
    sys.exit(main(sys.argv))
  File "./pgtune", line 687, in main
    wizard_tune(config, options, settings)
  File "./pgtune", line 593, in wizard_tune
    if settings.memory_unit(key):
  File "./pgtune", line 402, in memory_unit
    return (self.param_to_dict[setting])['memory_unit']
KeyError: 'wal_buffers'
```

**Comment by andreif** [comment]
It will be fixed e.g. via #18, you can also try [andreif@`allthethings`](https://github.com/andreif/pgtune/tree/allthethings) which contains even some other fixes.
